In [ ]:
import torch
from torch import nn # nn neural network building block
import numpy as np
import matplotlib.pyplot as plt


torch.__version__

'2.11.0+cpu'

#BUILDING A MODEL

* **`nn.Module`** contains the larger building blocks (layers)
* **`nn.Parameter`** contains the smaller parameters like weights and biases (put these together to make nn.Module(s))
* **`forward()`** tells the larger blocks how to make calculations on inputs (tensors full of data) within nn.Module(s)
* **`torch.optim`** contains optimization methods on how to improve the parameters within nn.Parameter to better represent input data

In [ ]:
class LinearRegressionModel(nn.Module): # <--- this is subclass , this give access/ inherid all functionality from nn.Module
  def __init__(self) -> None: # <--- This is the constructor. It's the method that runs automatically whenever you create a new instance of the class.
    super().__init__()# <---- gives you access to the parent class (nn.Module)
    self.weights = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float32)) # <--- used with Module s - when they’re assigned as Module attributes they are automatically added to the list of its parameters.

    self.bias = nn.Parameter(torch.rand(1, requires_grad=True, dtype=torch.float32))

  def forward(self, x:torch.Tensor) -> torch.Tensor: # x is the input data, "->" means this function is expected to return a torch.Tensor.
      return self.weights * x + self.bias # linear regression


In [ ]:
model_1 = LinearRegressionModel()
model_1.state_dict()

OrderedDict([('weights', tensor([0.7418])), ('bias', tensor([0.2262]))])

In [ ]:
list(model_1.parameters())

[Parameter containing:
 tensor([0.7418], requires_grad=True),
 Parameter containing:
 tensor([0.2262], requires_grad=True)]

In [ ]:
type(nn.parameter), type(nn.Parameter)

(module, torch.nn.parameter._ParameterMeta)

#TRAINING

Right now our model is making predictions using random parameters to make calculations, it's basically guessing (randomly).
To fix that, we can update its internal parameters (I also refer to parameters as patterns), the weights and bias values we set randomly using nn.Parameter() and torch.randn() to be something that better represents the data.

In [ ]:
X_test

tensor([[0.8000],
        [0.8200],
        [0.8400],
        [0.8600],
        [0.8800],
        [0.9000],
        [0.9200],
        [0.9400],
        [0.9600],
        [0.9800]])

In [ ]:
with torch.inference_mode():
  y_pre = model_1(X_test)

In [ ]:
y_pre

tensor([[0.8196],
        [0.8344],
        [0.8493],
        [0.8641],
        [0.8789],
        [0.8938],
        [0.9086],
        [0.9234],
        [0.9383],
        [0.9531]])

In [ ]:
y_test

tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

In [ ]:
loss = nn.L1Loss() #takes x, y where x is the predicted value and y is the targetted value

In [ ]:
#learn about NN

##Backpropagation and Gradient descent



In [ ]:
optimiser = torch.optim.SGD(params = model_1.parameters(), #assign the parameter of the model for optimizing
                            lr = 0.01 #how much the optimizer change the parameter in each step
                            )

##Building a training loop
1. Loop through the data
2. Forword pass (this involves moving data through the model's forward funtion `forward()`) to make prediction on data - also called forward propagation.
3. Calculating the loss by comparing the predicted value with target value.
4. Optimising it

##__Loss Function__
###Parameters:-
-> `size_average(bool, optional)` By default losses are averaged over each loss element in the batch and when set to `false`, the losses are instead summed for each minibatch. Ignored when `reduce` is `false`.

->`reduce(bool, optional)` When reduce is `false`, returns a loss per batch element instead and ignores `size_average`. Default: `True`

->`reduction(str, optional)` `mean`: the sum of the output will be divided by the number of elements in the output, `sum`: the output will be summed. __size_average__ and __reduce__ are in the process of being deprecated, and in the meantime, specifying either of those two args will override `reduction`. Default `mean`.
