In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


#**Fundamentals of Tensor**



In [ ]:
#scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
#vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
#dimention
vector.ndim

1

In [ ]:
#MATRIX
MATRIX = torch.tensor([[1,2,3],[8,2,1]])
MATRIX

tensor([[1, 2, 3],
        [8, 2, 1]])

In [ ]:
MATRIX.ndim

2

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,7],[89,1,4],[12,54,2]]])
TENSOR

tensor([[[ 1,  2,  7],
         [89,  1,  4],
         [12, 54,  2]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
##Shape
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensor

In [ ]:
random_tensor = torch.rand(size=(2,3,4))
random_tensor

tensor([[[0.2450, 0.5591, 0.2794, 0.5089],
         [0.4599, 0.9903, 0.0181, 0.7064],
         [0.4792, 0.8117, 0.8264, 0.5488]],

        [[0.8408, 0.3721, 0.4093, 0.9208],
         [0.2148, 0.0194, 0.4883, 0.2385],
         [0.3622, 0.7043, 0.2900, 0.7255]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224)) #height ,  width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(1,3,4))
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###Creating a range of tensors and tensor-like

In [ ]:
new_tensor = torch.arange(0,10,2)

In [ ]:
zeroes = torch.zeros_like(input=new_tensor)
zeroes

tensor([0, 0, 0, 0, 0])

### Tensor Datatype

In [ ]:
Tensor_float32 = torch.tensor(random_tensor, dtype=None, device=None, requires_grad=False)
Tensor_float32

/tmp/ipykernel_748/3730317062.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  Tensor_float32 = torch.tensor(random_tensor, dtype=None, device=None, requires_grad=False)


tensor([[[0.2450, 0.5591, 0.2794, 0.5089],
         [0.4599, 0.9903, 0.0181, 0.7064],
         [0.4792, 0.8117, 0.8264, 0.5488]],

        [[0.8408, 0.3721, 0.4093, 0.9208],
         [0.2148, 0.0194, 0.4883, 0.2385],
         [0.3622, 0.7043, 0.2900, 0.7255]]])

In [ ]:
Tensor_float32.dtype

torch.float32

In [ ]:
random_float16_tensor = Tensor_float32.type(torch.half)
random_float16_tensor.dtype

torch.float16

In [ ]:
random_float16_tensor

tensor([[[0.2450, 0.5591, 0.2793, 0.5088],
         [0.4600, 0.9902, 0.0181, 0.7065],
         [0.4792, 0.8115, 0.8267, 0.5488]],

        [[0.8408, 0.3721, 0.4092, 0.9209],
         [0.2148, 0.0193, 0.4883, 0.2385],
         [0.3621, 0.7041, 0.2900, 0.7256]]], dtype=torch.float16)

In [ ]:
random_float16_tensor*Tensor_float32

tensor([[[6.0022e-02, 3.1259e-01, 7.8030e-02, 2.5892e-01],
         [2.1152e-01, 9.8063e-01, 3.2909e-04, 4.9908e-01],
         [2.2964e-01, 6.5869e-01, 6.8317e-01, 3.0119e-01]],

        [[7.0699e-01, 1.3846e-01, 1.6746e-01, 8.4794e-01],
         [4.6148e-02, 3.7449e-04, 2.3843e-01, 5.6883e-02],
         [1.3113e-01, 4.9590e-01, 8.4124e-02, 5.2640e-01]]])

### Getting information from the tensor

In [ ]:
tensor = torch.rand(size=(2,2,2))
tensor

tensor([[[0.6173, 0.8602],
         [0.8946, 0.5570]],

        [[0.8188, 0.7935],
         [0.2462, 0.4186]]])

In [ ]:
#addition
tensor + 10

tensor([[[10.6173, 10.8602],
         [10.8946, 10.5570]],

        [[10.8188, 10.7935],
         [10.2462, 10.4186]]])

In [ ]:
#multiplication
tensor * 10

tensor([[[6.1727, 8.6020],
         [8.9463, 5.5697]],

        [[8.1877, 7.9354],
         [2.4615, 4.1865]]])

In [ ]:
torch.mul(tensor, 20)

tensor([[[12.3454, 17.2041],
         [17.8927, 11.1394]],

        [[16.3754, 15.8708],
         [ 4.9230,  8.3729]]])

In [ ]:
new = torch.rand(2,2,2)
new, tensor

(tensor([[[0.5852, 0.7348],
          [0.6220, 0.2648]],
 
         [[0.6234, 0.7992],
          [0.5876, 0.0075]]]),
 tensor([[[0.6173, 0.8602],
          [0.8946, 0.5570]],
 
         [[0.8188, 0.7935],
          [0.2462, 0.4186]]]))

In [ ]:
new*tensor

tensor([[[0.5371, 0.8340],
         [0.7468, 0.1629]],

        [[0.1579, 0.0958],
         [0.1524, 0.2104]]])

In [ ]:
# use tensor.matmul()
matrix_1 = torch.tensor([[1,2],
                         [2,7]])
matrix_2 = torch.tensor([[7,2],
                         [23,4]])

matrix_1,matrix_2


(tensor([[1, 2],
         [2, 7]]),
 tensor([[ 7,  2],
         [23,  4]]))

In [ ]:
torch.matmul(matrix_2, matrix_1)

tensor([[11, 28],
        [31, 74]])

In [ ]:
matrix_3 = torch.tensor([1,2,3])
torch.matmul(matrix_3, matrix_3)

tensor(14)

In [ ]:
matrix_3.ndim

1

In [ ]:
matrix_1.ndim, matrix_1.shape

(2, torch.Size([2, 2]))

###Shape Error

In [ ]:
matrix_1.T

tensor([[1, 2],
        [2, 7]])

In [ ]:
x = torch.arange(1,100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.max()

tensor(91)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x.type(torch.float16).mean()

tensor(46., dtype=torch.float16)

# Reshaping , stacking, squeezing, and unsqueezing tensors

* Reshaping  - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combines multiple tensor on top of each other (vstack) or side by side
* squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimention to a target tensor
* Permute - Return a view of the input with dimensions permute(swapped) in a certain way and shares same memory

In [ ]:
import torch
x = torch.arange(1.,11.)
x, x.shape, x.ndim

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 1)

In [ ]:
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.ndim

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 2)

In [ ]:
x.reshaped = x.reshape(1,10)
x.reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
#chage the view
z = x.view(2,5) #same memory as the original tensor
z,x

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
z = x.view(1,10)

In [ ]:
#Stack tensors on top of other tensors

#x_stacked = torch.stack([x,z,x,x])#should be of same size
x_stacked = torch.stack([x,x,x])
x_stacked, x_stacked.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 2)

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked, x_stacked.ndim, x_stacked.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 2,
 torch.Size([4, 10]))

In [ ]:
x = torch.zeros(2,1,2,1,2)
x, x.ndim

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 5)

In [ ]:
y  = x.squeeze()
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
y.size()

torch.Size([2, 2, 2])

In [2]:
import torch

In [4]:
tensor = torch.arange(1,11)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
tensor_reshape = tensor.reshape(1,2,5)
tensor_reshape

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]])

In [7]:
new_tensor = torch.zeros(2,1,2,1,2)
new_tensor

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [8]:
new_tensor_squeeze = new_tensor.squeeze()
new_tensor_squeeze

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [16]:
new_tensor_unsqueeze = new_tensor_squeeze.unsqueeze(dim=1).unsqueeze(dim=3)
new_tensor_unsqueeze

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

###Permute

In [33]:
tensor_5 = torch.rand(size=(3,2,5))
tensor_5, tensor_5.size()


(tensor([[[0.5487, 0.5797, 0.9198, 0.2773, 0.9554],
          [0.7494, 0.8069, 0.1892, 0.9186, 0.1258]],
 
         [[0.0733, 0.1692, 0.9131, 0.6506, 0.8526],
          [0.3342, 0.5371, 0.5936, 0.0688, 0.5066]],
 
         [[0.0587, 0.2177, 0.7798, 0.8677, 0.8939],
          [0.1533, 0.0380, 0.0330, 0.8497, 0.1249]]]),
 torch.Size([3, 2, 5]))

In [34]:
tensor_5 = torch.permute(tensor_5, (2,0,1)) # <---- Index
tensor_5

tensor([[[0.5487, 0.7494],
         [0.0733, 0.3342],
         [0.0587, 0.1533]],

        [[0.5797, 0.8069],
         [0.1692, 0.5371],
         [0.2177, 0.0380]],

        [[0.9198, 0.1892],
         [0.9131, 0.5936],
         [0.7798, 0.0330]],

        [[0.2773, 0.9186],
         [0.6506, 0.0688],
         [0.8677, 0.8497]],

        [[0.9554, 0.1258],
         [0.8526, 0.5066],
         [0.8939, 0.1249]]])

In [35]:
tensor_5.size(), tensor_5.type(torch.float16)

(torch.Size([5, 3, 2]),
 tensor([[[0.5488, 0.7495],
          [0.0733, 0.3342],
          [0.0587, 0.1533]],
 
         [[0.5796, 0.8071],
          [0.1692, 0.5371],
          [0.2177, 0.0380]],
 
         [[0.9199, 0.1892],
          [0.9131, 0.5938],
          [0.7798, 0.0331]],
 
         [[0.2773, 0.9185],
          [0.6504, 0.0688],
          [0.8677, 0.8496]],
 
         [[0.9556, 0.1257],
          [0.8525, 0.5063],
          [0.8940, 0.1249]]], dtype=torch.float16))

##Indexing

In [40]:
tensor = torch.rand(size=(2,3,3)).reshape(2,9,1)

In [41]:
tensor

tensor([[[0.2520],
         [0.3466],
         [0.1104],
         [0.6884],
         [0.0193],
         [0.7154],
         [0.5566],
         [0.7657],
         [0.0960]],

        [[0.7485],
         [0.0051],
         [0.8269],
         [0.7140],
         [0.9231],
         [0.7499],
         [0.7082],
         [0.3977],
         [0.5375]]])

In [47]:
tensor[1,5,0]

tensor(0.7499)

In [54]:
tensor[0 ,: ,0]

tensor([0.2520, 0.3466, 0.1104, 0.6884, 0.0193, 0.7154, 0.5566, 0.7657, 0.0960])

In [60]:
new_tensor = torch.arange(1,10).reshape(1,3,3)

In [61]:
new_tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [66]:
new_tensor[:,1,1]

tensor([5])

In [70]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,9.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [80]:
array.dtype #default float64

dtype('float64')

In [81]:
torch.arange(1.0,11.0).dtype #default float32

torch.float32

In [84]:
new_array = np.arange(1,11)
new_tensor = torch.from_numpy(new_array) # assign new memory
new_tensor.dtype, new_array.dtype

(torch.int64, dtype('int64'))

In [85]:
new_tensor = torch.arange(1,11)
new_tensor.dtype

torch.int64

In [92]:
#tensor to NumPy
tensor = torch.arange(1,11) #int64 large
numpy_tensor = tensor.numpy() #new memory alocation
tensor.dtype,  numpy_tensor.dtype

(torch.int64, dtype('int64'))

In [93]:
tensor = torch.ones(7)
tensor.dtype, tensor

(torch.float32, tensor([1., 1., 1., 1., 1., 1., 1.]))

## random out of random again - again

